name: Windows_RDP_Safe
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup RDP
        run: |
          net user "Colabuser" "Reelspro@123" /add
          net localgroup administrators "Colabuser" /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - name: Start Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          .\ngrok\ngrok.exe config add-authtoken "3AAePsUlIPdcY8QA4tL93r8xP7x_2MB6nDNNMw692aCGmfFHZ"
          Start-Process -NoNewWindow -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp --region eu 3389"
          Start-Sleep -Seconds 10
      - name: Get RDP Info
        run: |
          curl --silent http://127.0.0.1:4040/api/tunnels | ForEach-Object { $_ | ConvertFrom-Json } | Select-Object -ExpandProperty tunnels | Select-Object -ExpandProperty public_url
          Write-Host "User: Colabuser | Pass: Reelspro@123"
      - name: Keep Alive
        run: Start-Sleep -Seconds 21600
